name: Wetter-Bot

on:
  schedule:
    - cron: "30 3 * * *"   # täglich 5:30 Uhr Schweiter Sommerzeit
  workflow_dispatch:        # manueller Start zum Testen

jobs:
  sende-wetter:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:

      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
      
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: Wetter-Bot ausführen
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python weather_bot.py
